apiVersion: v1
kind: Service
metadata:
  name: Collaboration and workflow management
  labels:
    app: Collaboration and workflow management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Collaboration and workflow management