apiVersion: v1
kind: Service
metadata:
  name: Upload and storage infrastructure
  labels:
    app: Upload and storage infrastructure
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Upload and storage infrastructure