apiVersion: v1
kind: Service
metadata:
  name: User management and access control
  labels:
    app: User management and access control
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User management and access control