apiVersion: v1
kind: Service
metadata:
  name: Search and retrieval functionality
  labels:
    app: Search and retrieval functionality
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Search and retrieval functionality